# Generated by Django 3.1.5 on 2021-01-10 00:40

# Third Party Library
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Chat id')),
                ('order_id', models.IntegerField(verbose_name='Order id')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='WAITING', max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Finished at')),
            ],
        ),
    ]
